### ISSUE TITLE
run_cls.sh fails to run because of missing files: `rte-x1.json` and `qnli-x1.json`

### ISSUE THREAD

**Issue by adivekar-utexas** [jiacheng-ye/ZeroGen#1]
Hi  Jiacheng, could you please provide these files? It is needed to run the repo.

**Comment by jiacheng-ye** [comment]
Hello, for rte and qnli, we didn't generate the `xxx_x1.json` file as we directly use the premise/context part in rte/qnli. 
Check out the code here
https://github.com/jiacheng-ye/ZeroGen/blob/0581de739a35b7bc4a0f533adea20b2830a694fa/main.py#L184

**Comment by adivekar-utexas** [comment]
Hi @jiacheng-ye , thank you for the response!
However, `run_cls.sh` seems to expect `xxx_x1.json`, and thus fails when calling it via: `bash scripts/run_cls.sh`. 

I think the reason is because of this command, which tries to run `main.py` with a flag `--task_file tasks/${task}/${task}-x1.json`: https://github.com/jiacheng-ye/ZeroGen/blob/master/scripts/run_cls.sh#L50

Could you please check this?

**Comment by jiacheng-ye** [comment]
Thanks. You don't need to run the `Generating Context C with PLM` stage for rte and qnli as we directly use the premise or context provided in the training set. So just comment out this line https://github.com/jiacheng-ye/ZeroGen/blob/0581de739a35b7bc4a0f533adea20b2830a694fa/scripts/run_cls.sh#L58-L59

**Comment by adivekar-utexas** [comment]
Got it, thanks!
